version: '3.1'

services:

  db:
    image: postgres:16.0-alpine3.18
    container_name: db
    restart: always
    healthcheck:
      test: "exit 0"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/var/lib/postgresql/data

  users:
    image: users:latest
    depends_on:
      db:
        condition: service_healthy
    container_name: usersc
    ports:
      - 3001:3001
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres?schema=public
      - HISTORY_HOST=localhost

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

